- title: "เมาส์บลูทูธพกพา"
  subtitle: "เสียงเงียบ น้ำหนักเบา"
  url: "https://s.shopee.co.th/9Uxw5xcV7d"
  image: "/assets/images/Mouse.webp"

- title: "ขาตั้งโน๊ตบุ๊ค"
  subtitle: "พกพาสะดวก ปรับระดับได้เยอะ"
  url: "https://s.shopee.co.th/6fdkhqD8A6"
  image: "/assets/images/LaptopStand.webp"

- title: "จอยเกม PC"
  subtitle: "จอยไร้สาย รองรับหลายอุปกรณ์"
  url: "https://s.shopee.co.th/7Aa1HIPzJ0"
  image: "/assets/images/Controller.webp"

- title: "ขาตั้งกล้อง TNW"
  subtitle: "พกพาสะดวก วัสดุแข็งแรง สูง 1.8 เมตร"
  url: "https://s.shopee.co.th/2g7fFCe7ZD"
  image: "/assets/images/CameraStand.webp"

- title: "พาวเวอร์แบงค์ 30,000 mAh"
  subtitle: "ความจุเยอะ ชาร์จเร็ว 120W"
  url: "https://s.shopee.co.th/6AhXQEcjL7"
  image: "/assets/images/Powerbank.webp"
